services:
  server:
    build: .
    container_name: server
    ports:
      - "3001:3001"

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'

volumes:
  db-data: